app:LinkStack.o LinkList.o tframe.o
	gcc LinkStack.o LinkList.o tframe.o -o app

LinkStack.o:LinkStack.c
	gcc -c LinkStack.c

LinkList.o:LinkList.c
	gcc -c LinkList.c

tframe.o:tframe.c
	gcc -c tframe.c
